POST http://localhost:3004/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhdmlwdWx1IiwiaWQiOiI1YTg4ZTI1ODBkNTJjOTc2OGMyMzA4NjkiLCJpYXQiOjE1MTg5MjAzNjh9.x4-tet_gl3-JeuDd300tHrkBXkN76cRuSUwIIWxffDs

{
    "title": "Ruby -blogi",
    "author": "Matti Meikäläinen",
    "url": "",
    "likes": 0,
    "userId": "5a88d600c52c3f585196c251"
}